### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by Vero-Fran** [automl/ParameterImportance#129]
Hi,

I installed all the needed packages to use pyimp on Windows 10. Or so I tought :) However, when trying to run the pimp command, I get the following issue. Does someone know how to fix this?

I know there is a warning about smac that might not be ok with windows but smac seems to be installed just fine...

Thank you in advance for your time.

```
C:\Computing\HCT_tuning\exec_HCT_param_1\pyimp-input>pimp -S scenario.txt -H runhistory.json -M all

Detected unsupported operating system: win32. Please be aware, that SMAC might not run on this system.
Traceback (most recent call last):
  File "c:\computing\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\computing\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Computing\Python\Python39\Scripts\pimp.exe\__main__.py", line 4, in <module>
  File "c:\computing\python\python39\lib\site-packages\pimp\pimp.py", line 15, in <module>
    from smac.scenario.scenario import Scenario
  File "c:\computing\python\python39\lib\site-packages\smac\scenario\scenario.py", line 7, in <module>
    from smac.utils.io.input_reader import InputReader
  File "c:\computing\python\python39\lib\site-packages\smac\utils\io\input_reader.py", line 4, in <module>
    from smac.configspace import pcs, pcs_new, ConfigurationSpace
  File "c:\computing\python\python39\lib\site-packages\smac\configspace\__init__.py", line 3, in <module>
    from ConfigSpace import ConfigurationSpace, Configuration, Constant, \
  File "c:\computing\python\python39\lib\site-packages\ConfigSpace\__init__.py", line 37, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace\configuration_space.pyx", line 38, in init ConfigSpace.configuration_space
  File "c:\computing\python\python39\lib\site-packages\ConfigSpace\nx\__init__.py", line 36, in <module>
    from ConfigSpace.nx.algorithms import (
  File "c:\computing\python\python39\lib\site-packages\ConfigSpace\nx\algorithms\__init__.py", line 1, in <module>
    from ConfigSpace.nx.algorithms.dag import (
  File "c:\computing\python\python39\lib\site-packages\ConfigSpace\nx\algorithms\dag.py", line 2, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (c:\computing\python\python39\lib\fractions.py)
```

**Comment by tirkarthi** [comment]
This seems to have been fixed in https://github.com/automl/ConfigSpace/commit/5c180915fb5b8a191779f0d81cdb4d613ad04d25
